import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Provider from "./Provider";
import { SubHeader } from "@/components/subHeader/SubHeader";
import SearchBox from "@/components/searchBox/SearchBox";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				<Provider>
					<Header />
          <SubHeader />
          <SearchBox />
					{children}
				</Provider>
			</body>
		</html>
	);
}
